#!/bin/bash

SCRIPT_DIR="$(dirname "$0")"
. "$SCRIPT_DIR/common.sh"

readJvmOptionsFile "jvm-client.options"

JAVA_OPTS_ARRAY=(\
$JDK_OPTS \
"-Dhazelcast.client.config=$HAZELCAST_HOME/config/hazelcast-client.yaml" \
$JVM_OPTIONS \
$JAVA_OPTS \
)

# TODO update command line class
$JAVA "${JAVA_OPTS_ARRAY[@]}" -cp "$CLASSPATH" com.hazelcast.client.console.HazelcastCommandLine "$@"
