#!/usr/bin/env bash

function findScriptDir() {
  CURRENT=$PWD

  DIR=$(dirname "$0")
  cd "$DIR" || exit
  TARGET_FILE=$(basename "$0")

  # Iterate down a (possible) chain of symlinks
  while [ -L "$TARGET_FILE" ]
  do
      TARGET_FILE=$(readlink "$TARGET_FILE")
      DIR=$(dirname "$TARGET_FILE")
      cd "$DIR" || exit
      TARGET_FILE=$(basename "$TARGET_FILE")
  done

  SCRIPT_DIR=$(pwd -P)
  # Restore current directory
  cd "$CURRENT" || exit
}

findScriptDir

. "$SCRIPT_DIR"/common.sh

# HAZELCAST_CONFIG holds the configuration path.
# If the the path is relative, it is relative to the Hazelcast installation directory (HAZELCAST_HOME).
# The path can be absolute.
# By default, it is set to $HAZELCAST_HOME/config/hazelcast.xml, with fallback to $HAZELCAST_HOME/config/hazelcast.yaml
# and to $HAZELCAST_HOME/config/hazelcast.yml if the xml file is not present.
if [ -z "$HAZELCAST_CONFIG" ]; then
    HAZELCAST_CONFIG="config/hazelcast.xml"
    if [ ! -f "$HAZELCAST_HOME/$HAZELCAST_CONFIG" ]; then
        HAZELCAST_CONFIG="config/hazelcast.yaml"
    fi
    if [ ! -f "$HAZELCAST_HOME/$HAZELCAST_CONFIG" ]; then
        HAZELCAST_CONFIG="config/hazelcast.yml"
    fi

    if [ ! -f "$HAZELCAST_HOME/$HAZELCAST_CONFIG" ]; then
        echo "Configuration file is missing. Create hazelcast.[xml|yaml|yml] in $HAZELCAST_HOME/config or set the HAZELCAST_CONFIG environment variable."
        exit 1
    fi
fi
# if the first character is /, then this is an absolute path, use as is
# otherwise prepend (HAZELCAST_HOME)
if [ "${HAZELCAST_CONFIG:0:1}" != "/" ]; then
  HAZELCAST_CONFIG="$HAZELCAST_HOME/$HAZELCAST_CONFIG"
fi

if [ "${PROMETHEUS_PORT}" ]; then
    echo "Prometheus enabled on port ${PROMETHEUS_PORT}"
    PROMETHEUS="-javaagent:${HAZELCAST_HOME}/lib/jmx_prometheus_javaagent-${prometheus.version}.jar=${PROMETHEUS_PORT}:${HAZELCAST_HOME}/config/jmx_agent_config.yaml"
fi

readJvmOptionsFile "jvm.options"

if [ "$HAZELCAST_LICENSE_KEY" ]; then
    LICENSING_OPT="-Dhazelcast.enterprise.license.key=${HAZELCAST_LICENSE_KEY}"
fi

JAVA_OPTS_ARRAY=(\
$JDK_OPTS \
"-Dhazelcast.logging.type=log4j2" \
"-Dlog4j.configurationFile=file:$HAZELCAST_HOME/config/log4j2.properties" \
"-Dhazelcast.config=$HAZELCAST_CONFIG" \
"-Djet.custom.lib.dir=$HAZELCAST_HOME/custom-lib" \
$PROMETHEUS \
$LICENSING_OPT\
$JVM_OPTIONS \
$JAVA_OPTS \
)

if [ -z "$LOGGING_LEVEL" ]; then
    export LOGGING_LEVEL="INFO"
fi

if [ "$(arch)" == "s390x" ]; then
  export LOGGING_PATTERN="%d [%highlight{\${LOG_LEVEL_PATTERN:-%5p}}{FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=magenta}][%style{%t{1.}}{cyan}] [%style{%-10c}{blue}]: %m%n"
else
  export LOGGING_PATTERN="%d [%highlight{\${LOG_LEVEL_PATTERN:-%5p}}{FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=magenta}] [%style{%t{1.}}{cyan}] [%style{%c{1.}}{blue}]: %m%n"
fi

J_OPTS=""
for arg in "${JAVA_OPTS_ARRAY[@]}"
do
  if [ "$J_OPTS" = "" ]; then
    J_OPTS="$arg"
  else
    J_OPTS="$J_OPTS,$arg"
  fi
done

HZ_CMD="exec ${JAVA} -cp ${CLASSPATH} ${JAVA_OPTS_ARRAY[@]} com.hazelcast.commandline.HazelcastServerCommandLine"

echo "########################################"
echo "# JAVA=$JAVA"
echo "# JAVA_OPTS=${JAVA_OPTS_ARRAY[*]}"
echo "# CLASSPATH=$CLASSPATH"
echo "########################################"

if [ "$1" = "start" ] ; then

  ${HZ_CMD} "$@" "--JAVA_OPTS=$J_OPTS"
else
  ${HZ_CMD} "$@"
fi
