#!/bin/bash

function findScriptDir() {
  DIR=$(dirname "$0")
  cd "$DIR" || exit
  TARGET_FILE=$(basename "$0")

  # Iterate down a (possible) chain of symlinks
  while [ -L "$TARGET_FILE" ]
  do
      TARGET_FILE=$(readlink "$TARGET_FILE")
      DIR=$(dirname "$TARGET_FILE")
      cd "$DIR" || exit
      TARGET_FILE=$(basename "$TARGET_FILE")
  done

  SCRIPT_DIR=$(pwd -P)
}

findScriptDir
. "$SCRIPT_DIR/common.sh"

readJvmOptionsFile "jvm-client.options"

JAVA_OPTS_ARRAY=(\
$JDK_OPTS \
$JVM_OPTIONS \
$JAVA_OPTS \
)

$JAVA "${JAVA_OPTS_ARRAY[@]}" -cp "$CLASSPATH" com.hazelcast.client.console.HazelcastCommandLine "$@"
