#!/bin/bash
#
# Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PROCESS_MATCHER="com.hazelcast.commandline.HazelcastServerCommandLine"

if [ "$1" = "help" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Usage : $0"
  echo "Used to stop any running instances of HazelcastServerCommandLine."
  echo "Finds any processes matching \"$PROCESS_MATCHER\" and stops all of them."
  exit 1
fi

PIDS=$(ps ax | grep $PROCESS_MATCHER | grep -v grep | awk '{print $1}')

if [ -z "$PIDS" ]; then
  echo "No Hazelcast server found to stop"
  exit 1
else
  kill -s TERM $PIDS
  echo "Stopped Hazelcast instances with the following PIDs:"
  echo "$PIDS"
fi
