#!/bin/bash

if [ "$1" = "help" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Usage : hz-stop"
  echo "Used to stop any running instances of HazelcastMemberStarter."
  echo "Finds any processes matching com.hazelcast.core.server.HazelcastMemberStarter and stops all of them."
  exit 1
fi

PIDS=$(ps ax | grep com.hazelcast.core.server.HazelcastMemberStarter | grep -v grep | awk '{print $1}')

if [ -z "$PIDS" ]; then
  echo "No Hazelcast server found to stop"
  exit 1
else
  kill -s TERM $PIDS
  echo "Stopped Hazelcast instances with the following PIDs:"
  echo "$PIDS"
fi
