version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "02:00"
    labels:
      - "Source: Internal"
      - "dependencies"
    open-pull-requests-limit: 100
    commit-message:
      prefix: ""
    ignore:
      # it's our supported version, no need to upgrade
      - dependency-name: "org.springframework.version"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "02:00"
