[appendix]
= Jet Version Compatibility

The following rules currently apply for Jet for compile time
and runtime compatibility.

== Semantic Versioning

Hazelcast Jet uses https://semver.org/[Semantic Versioning] which
can be summarized as follows:

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.

This means that a Jet job written using Pipeline API in a previous
minor version should compile in later minor versions.

However some exceptions apply:

* Classes in `com.hazelcast.jet.core` package which form the
<<expert-zone, Core API>> of Jet only provide PATCH level compatibility guarantee.
* Types and methods annotated with `@EvolvingApi` only provide PATCH level
compatibility guarantee. These are typically new features where the API is
subject to further changes.
* Classes in `impl` packages do not provide any compatibility
guarantees between versions and should not be used.

== Summary Table

The compatibility guarantees can be summarized as follows:

[%header]
|===
|Type|Component|Guarantee
|Compile Time|Job API|MINOR
|Compile Time|Pipeline API|MINOR
|Compile Time|Core API|PATCH
|Runtime|Member to Member|NONE
|Runtime|Management Center to Member|NONE
|Runtime|Client to Member|PATCH
|Runtime|Job State|PATCH
|Runtime|Command Line Tools|MINOR
|Runtime|Configuration XML files|PATCH
|Runtime|Metrics (JMX)|PATCH
|===

== Runtime Compatibility

=== Members

Jet requires that all members in a cluster use the same PATCH version.
When updating Jet to a newer PATCH version, the whole cluster must be
shutdown and restarted with the newer version at once.

=== Management Center

Management Center, like members, is only compatible with the same
PATCH version. This means that Management Center and the cluster
must have the exact same PATCH version to be compatible.

=== Clients

Jet clients are compatible with the members running on the same MINOR
version. This means that a client using an older or newer PATCH version
should be able to connect and work with a cluster that's running a different
PATCH version.

== Job State Compatibility

Job state is only compatible across the same MINOR version and only
backwards-compatible i.e. a newer PATCH version is be able to understand
the job state from a previous PATCH version.

This means that if you have a running job, using the Job Upgrade
and Lossless Cluster Restart features you are able to upgrade the cluster 
to a newer PATCH version without losing the state of a running job.

== Command Line Tools and Configuration Files

The command line tools provided such as `jet` and the configuration
XML files are backwards-compatible between MINOR versions. This means
that when upgrading a cluster to a new minor version, the XML configuration
for the previous version can be used without any modification.

== Metrics

Jet currently provides metrics to Management Center and also through
other means such as JMX. The metrics names may change between MINOR
versions but not between PATCH versions.

[appendix]
[[system-properties]]
= System Properties

The table below lists the system properties supported by Jet. Jet also
supports the system properties defined by Hazelcast IMDG, please see the
System properties chapter in Hazelcast IMDG Reference Manual.

NOTE: When you want to reconfigure a system property, you need to
restart the members for which the property is modified.

[cols="2,1,1,6a"]
.System Properties
|===
|Property Name
| Default Value
| Type
| Description

|`jet.job.scan.period`
|5000
|long [milliseconds]
|Jet will periodically check for new jobs to start and perform cleanup
of unused resources. This property configures how often this check and
cleanup will be done. Value is in milliseconds.

|`jet.shutdownhook.enabled`
|true
|boolean
|Whether a JVM shutdown hook is registered to shutdown the node
gracefully when the process is terminated. The shutdown hook will
terminate all running jobs and then gracefully terminate the note, in a
way that is equivalent to calling JetInstance.shutdown().

|`jet.job.results.ttl.seconds`
|604800 (7 days)
|long [seconds]
|Maximum number of time in seconds the job results will be kept in the
cluster. They will be automatically deleted after this period is
reached.

|`jet.job.results.max.size`
|1000
|integer
|Maximum number of job results to keep in the cluster, the oldest
results will be automatically deleted after this size is reached.

|`jet.home`
|_Jet installation path_
|string
|Root of Jet installation. Used as default location for the Lossless
Cluster Restart store. By default it will be automatically set to the 
start of the Jet installation path.

|`jet.idle.cooperative.min.microseconds`
|25
|long [microseconds]
|The minimum time in microseconds the cooperative worker threads will
sleep if none of the tasklets made any progress. Lower values increase
idle CPU usage but may result in decreased latency. Higher values will
increase latency and very high values (>10000µs) will also limit
throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.cooperative.max.microseconds`
|500
|long [microseconds]
|The maximum time in microseconds the cooperative worker threads will
sleep if none of the tasklets made any progress. Lower values increase
idle CPU usage but may result in decreased latency. Higher values will
increase latency and very high values (>10000µs) will also limit
throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.noncooperative.min.microseconds`
|25
|long [microseconds]
|The minimum time in microseconds the non-cooperative worker threads
will sleep if none of the tasklets made any progress. Lower values
increase idle CPU usage but may result in decreased latency. Higher
values will increase latency and very high values (>10000µs) will also
limit throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.noncooperative.max.microseconds`
|5000
|long [microseconds]
|The maximum time in microseconds the non-cooperative worker threads
will sleep if none of the tasklets made any progress. Lower values
increase idle CPU usage but may result in decreased latency. Higher
values will increase latency and very high values (>10000µs) will also
limit throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|===


[appendix]
= Common Exceptions

You may see the following exceptions thrown when working with Jet:

* {jet-javadoc}/JetException.html[`JetException`]:
A general exception thrown if a job failure occurs. It has the original
exception as its cause.
* {jet-javadoc}/core/TopologyChangedException.html[`TopologyChangedException`]:
Thrown when a member participating in a job leaves the cluster. If
auto-restart is enabled, Jet will restart the job automatically, without
throwing the exception to the user.
* {jet-javadoc}/core/JobNotFoundException.html[`JobNotFoundException`]:
Thrown when the coordinator node is not able to find the metadata for a
given job.

There are also several Hazelcast exceptions that might be thrown when
interacting with `JetInstance`. For a description of Hazelcast IMDG
exceptions, please refer to the
{hz-refman}#common-exception-types[IMDG Reference manual].

[appendix]
[[phone-homes]]
= Phone Homes

Hazelcast uses phone home data to learn about the usage of Hazelcast Jet.

Hazelcast Jet instances call our phone home server initially when they
are started and then every 24 hours. This applies to all the instances
joined to the cluster.

== What is sent in?

The following information is sent in a phone home:

* Hazelcast Jet version
* Local Hazelcast Jet member UUID
* Download ID
* A hash value of the cluster ID
* Cluster size bands for 5, 10, 20, 40, 60, 100, 150, 300, 600 and > 600
* Number of connected clients bands of 5, 10, 20, 40, 60, 100, 150, 300, 600 and > 600
* Cluster uptime
* Member uptime
* Environment Information:
** Name of operating system
** Kernel architecture (32-bit or 64-bit)
** Version of operating system
** Version of installed Java
** Name of Java Virtual Machine
* Hazelcast IMDG Enterprise specific:
** Number of clients by language (Java, C++, C#)
** Flag for Hazelcast Enterprise
** Hash value of license key
** Native memory usage

== Phone Home Code

The phone home code itself is open source. Please see https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/util/PhoneHome.java[here].

== Disabling Phone Homes

Set the `hazelcast.phone.home.enabled` system property to false either
in the config or on the Java command line.

Starting with Hazelcast Jet 0.5, you can also disable the phone home
using the environment variable `HZ_PHONE_HOME_ENABLED`. Simply add the
following line to your `.bash_profile`:

----
export HZ_PHONE_HOME_ENABLED=false
----

== Phone Home URL

The URL used for phone home requests is

----
http://phonehome.hazelcast.com/ping
----

[appendix]
= FAQ

You can refer to the https://jet.hazelcast.org/faq/[FAQ] page to see the
answers to frequently asked questions related to topics such as the
relationship and differences between Hazelcast Jet and Hazelcast IMDG,
Jet's APIs and roadmap.

[appendix]
= License Questions

Hazelcast Jet is distributed using the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2],
therefore permissions are granted to use, reproduce and distribute it
along with any kind of open source and closed source applications.

Depending on the used feature-set, Hazelcast Jet has certain runtime
dependencies which might have different licenses. Following are
dependencies and their respective licenses.

== Embedded Dependencies

Embedded dependencies are merged (shaded) with the Hazelcast Jet
codebase at compile-time. These dependencies become an integral part of
the Hazelcast Jet distribution.

For license files of embedded dependencies, please see the `license`
directory of the Hazelcast Jet distribution, available at our
https://jet.hazelcast.org/download/[download page].

=== minimal-json

minimal-json is a JSON parsing and generation library which is a part of
the Hazelcast Jet distribution. It is used for communication
between the Hazelcast Jet cluster and the Management Center.

minimal-json is distributed under the
http://opensource.org/licenses/MIT[MIT license] and offers the same
rights to add, use, modify, and distribute the source code as the Apache
License 2.0 that Hazelcast uses. However, some other restrictions might
apply.

=== picocli

picocli is a command line parser which is used for the implementation of
`jet` command line tool.

picocli is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Runtime Dependencies

Depending on the used features, additional dependencies might be added
to the dependency set. Those runtime dependencies might have other
licenses. See the following list of additional runtime dependencies.

=== Apache Hadoop

Hazelcast integrates with Apache Hadoop and can use it as a data
 sink or source. Jet has a dependency on the libraries required to
 read from and write to the Hadoop File System.

Apache Hadoop is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Apache Kafka

Hazelcast integrates with Apache Kafka and can make use of it as a
data sink or source. Hazelcast has a dependency on Kafka client
libraries.

Apache Kafka is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Spring

Hazelcast integrates with Spring and can be configured using Spring
Context. Jet has a dependency on the libraries required to create a
Spring context.

Spring is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

