[appendix]
= Jet Version Compatibility

The following rules currently apply for Jet for compile time
and runtime compatibility.

== Semantic Versioning

Hazelcast Jet uses https://semver.org/[Semantic Versioning] which
can be summarized as follows:

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.

This means that a Jet job written using Pipeline API in a previous
minor version should compile in later minor versions.

However some exceptions apply:

* Classes in `com.hazelcast.jet.core` package which form the
<<expert-zone, Core API>> of Jet only provide PATCH level compatibility guarantee.
* Types and methods annotated with `@EvolvingApi` only provide PATCH level
compatibility guarantee. These are typically new features where the API is
subject to further changes.
* Classes in `impl` packages do not provide any compatibility
guarantees between versions and should not be used.

== Summary Table

The compatibility guarantees can be summarized as follows:

[%header]
|===
|Type|Component|Guarantee
|Compile Time|Job API|MINOR
|Compile Time|Pipeline API|MINOR
|Compile Time|Core API|PATCH
|Runtime|Member to Member|NONE
|Runtime|Management Center to Member|NONE
|Runtime|Client to Member|PATCH
|Runtime|Job State|PATCH
|Runtime|Command Line Tools|MINOR
|Runtime|Configuration XML files|PATCH
|Runtime|Metrics (JMX)|PATCH
|===

== Runtime Compatibility

=== Members

Jet requires that all members in a cluster use the same PATCH version.
When updating Jet to a newer PATCH version, the whole cluster must be
shutdown and restarted with the newer version at once.

=== Management Center

Management Center, like members, is only compatible with the same
PATCH version. This means that Management Center and the cluster
must have the exact same PATCH version to be compatible.

=== Clients

Jet clients are compatible with the members running on the same MINOR
version. This means that a client using an older or newer PATCH version
should be able to connect and work with a cluster that's running a different
PATCH version.

== Job State Compatibility

Job state is only compatible across the same MINOR version and only
backwards-compatible i.e. a newer PATCH version is be able to understand
the job state from a previous PATCH version.

This means that if you have a running job, using the Job Upgrade
and Lossless Cluster Restart features you are able to upgrade the cluster
to a newer PATCH version without losing the state of a running job.

== Command Line Tools and Configuration Files

The command line tools provided such as `jet` and the configuration
XML files are backwards-compatible between MINOR versions. This means
that when upgrading a cluster to a new minor version, the XML configuration
for the previous version can be used without any modification.

== Metrics

Jet currently provides metrics to Management Center and also through
other means such as JMX. The metrics names may change between MINOR
versions but not between PATCH versions.

[appendix]
[[system-properties]]
= System Properties

The table below lists the system properties supported by Jet. Jet also
supports the system properties defined by Hazelcast IMDG, please see the
System properties chapter in Hazelcast IMDG Reference Manual.

NOTE: When you want to reconfigure a system property, you need to
restart the members for which the property is modified.

[cols="2,1,1,6a"]
.System Properties
|===
|Property Name
| Default Value
| Type
| Description

|`jet.job.scan.period`
|5000
|long [milliseconds]
|Jet will periodically check for new jobs to start and perform cleanup
of unused resources. This property configures how often this check and
cleanup will be done. Value is in milliseconds.

|`jet.shutdownhook.enabled`
|true
|boolean
|Whether a JVM shutdown hook is registered to shutdown the node
gracefully when the process is terminated. The shutdown hook will
terminate all running jobs and then gracefully terminate the note, in a
way that is equivalent to calling JetInstance.shutdown().

|`jet.job.results.ttl.seconds`
|604800 (7 days)
|long [seconds]
|Maximum number of time in seconds the job results will be kept in the
cluster. They will be automatically deleted after this period is
reached.

|`jet.job.results.max.size`
|1000
|integer
|Maximum number of job results to keep in the cluster, the oldest
results will be automatically deleted after this size is reached.

|`jet.home`
|_Jet installation path_
|string
|Root of Jet installation. Used as default location for the Lossless
Cluster Restart store. By default it will be automatically set to the
start of the Jet installation path.

|`jet.idle.cooperative.min.microseconds`
|25
|long [microseconds]
|The minimum time in microseconds the cooperative worker threads will
sleep if none of the tasklets made any progress. Lower values increase
idle CPU usage but may result in decreased latency. Higher values will
increase latency and very high values (>10000µs) will also limit
throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.cooperative.max.microseconds`
|500
|long [microseconds]
|The maximum time in microseconds the cooperative worker threads will
sleep if none of the tasklets made any progress. Lower values increase
idle CPU usage but may result in decreased latency. Higher values will
increase latency and very high values (>10000µs) will also limit
throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.noncooperative.min.microseconds`
|25
|long [microseconds]
|The minimum time in microseconds the non-cooperative worker threads
will sleep if none of the tasklets made any progress. Lower values
increase idle CPU usage but may result in decreased latency. Higher
values will increase latency and very high values (>10000µs) will also
limit throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|`jet.idle.noncooperative.max.microseconds`
|5000
|long [microseconds]
|The maximum time in microseconds the non-cooperative worker threads
will sleep if none of the tasklets made any progress. Lower values
increase idle CPU usage but may result in decreased latency. Higher
values will increase latency and very high values (>10000µs) will also
limit throughput.

Note: the underlying `LockSupport.parkNanos(long)` call may actually
sleep longer depending on the operating system (up to 15000µs on
Windows). See the
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/[Hazelcast
blog post] about this subject  for more details.

|===


[appendix]
= Common Exceptions

You may see the following exceptions thrown when working with Jet:

* {jet-javadoc}/JetException.html[`JetException`]:
A general exception thrown if a job failure occurs. It has the original
exception as its cause.
* {jet-javadoc}/core/TopologyChangedException.html[`TopologyChangedException`]:
Thrown when a member participating in a job leaves the cluster. If
auto-restart is enabled, Jet will restart the job automatically, without
throwing the exception to the user.
* {jet-javadoc}/core/JobNotFoundException.html[`JobNotFoundException`]:
Thrown when the coordinator node is not able to find the metadata for a
given job.

There are also several Hazelcast exceptions that might be thrown when
interacting with `JetInstance`. For a description of Hazelcast IMDG
exceptions, please refer to the
{hz-refman}#common-exception-types[IMDG Reference manual].

[appendix]
[[phone-homes]]
= Phone Homes

Hazelcast uses phone home data to learn about the usage of Hazelcast Jet.

Hazelcast Jet instances call our phone home server initially when they
are started and then every 24 hours. This applies to all the instances
joined to the cluster.

== What is sent in?

The following information is sent in a phone home:

* Hazelcast Jet version
* Local Hazelcast Jet member UUID
* Download ID
* A hash value of the cluster ID
* Cluster size bands for 5, 10, 20, 40, 60, 100, 150, 300, 600 and > 600
* Number of connected clients bands of 5, 10, 20, 40, 60, 100, 150, 300, 600 and > 600
* Cluster uptime
* Member uptime
* Environment Information:
** Name of operating system
** Kernel architecture (32-bit or 64-bit)
** Version of operating system
** Version of installed Java
** Name of Java Virtual Machine
* Hazelcast IMDG Enterprise specific:
** Number of clients by language (Java, C++, C#)
** Flag for Hazelcast Enterprise
** Hash value of license key
** Native memory usage

== Phone Home Code

The phone home code itself is open source. Please see
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/util/PhoneHome.java[here].

== Disabling Phone Homes

Set the `hazelcast.phone.home.enabled` system property to false either
in the config or on the Java command line.

Starting with Hazelcast Jet 0.5, you can also disable the phone home
using the environment variable `HZ_PHONE_HOME_ENABLED`. Simply add the
following line to your `.bash_profile`:

----
export HZ_PHONE_HOME_ENABLED=false
----

== Phone Home URL

The URL used for phone home requests is

----
http://phonehome.hazelcast.com/ping
----

[appendix]
= Migration Guides

This appendix provides guidelines for upgrading to a new Hazelcast Jet
version. See also the
https://docs.hazelcast.org/docs/jet/release-notes/index.html[Release Notes]
document for the changes for each Hazelcast Jet release.

== Upgrading to Hazelcast Jet 4.0

Jet 4.0 is a major version release. According to the semantic versioning
we apply, this means that in version 4.0 some of the API has changed in
a breaking way and code written for 3.x may no longer compile against it.

=== Jet on IMDG 4.0

Jet 4.0 uses IMDG 4.0, which is also a major release with its own
breaking changes. For details see
https://docs.hazelcast.org/docs/rn/index.html[IMDG Release Notes]
and
https://docs.hazelcast.org/docs/latest/manual/html-single/#migration-guides[IMDG Migration Guides].

The most important changes we made and which have affected Jet too are
as follows:

* We renamed many packages and moved classes around. For details see the
https://docs.hazelcast.org/docs/rn/index.html#4-0[IMDG Release Notes].
The most obvious change is that many classes that used to be in the
general `com.hazelcast.core` package are now in specific packages like
`com.hazelcast.map` or `com.hazelcast.collection`.

* `com.hazelcast.jet.function`, the package containing serializable variants
of `java.util.function`, is now merged into `com.hazelcast.function`:
`BiConsumerEx`,`BiFunctionEx`,`BinaryOperatorEx`, `BiPredicateEx`,
`ComparatorEx`, `ComparatorsEx`, `ConsumerEx`, `FunctionEx`, `Functions`,
`PredicateEx`, `SupplierEx`, `ToDoubleFunctionEx`, `ToIntFunctionEx`,
`ToLongFunctionEx`.

* `EntryProcessor` and several other classes and methods received a cleanup
of their type parameters. See the
https://docs.hazelcast.org/docs/latest/manual/html-single/#introducing-lambda-friendly-interfaces[relevant section]
in the IMDG Migration Guide.

* The term "group" in configuration was replaced with "cluster". See the
code snippet below for an example. This changes a Jet Command Line
parameter as well (`-g/--groupName` renamed to `-n/--cluster-name`).
+
[source]
----
include::{javasource}/migration/Migration.java[tag=config1]
----

* `EventJournalConfig` moved from the top-level `Config` class to
data structure-specific configs (`MapConfig`,`CacheConfig`).
+
[source]
----
include::{javasource}/migration/Migration.java[tag=config2]
----

* `ICompletableFuture` was removed and replaced with the JDK-standard
`CompletionStage`. This affects the return type of async methods. See the
https://docs.hazelcast.org/docs/latest/manual/html-single/#removal-of-icompletablefuture[relevant section]
in the IMDG Migration Guide.

=== Jet API Changes

We made multiple breaking changes in Jet's own APIs too:

* `IMapJet`, `ICacheJet` and `IListJet`, which used to be Jet-specific
wrappers around IMDG's standard `IMap`, `ICache` and `IList`, were
removed. The methods that used to return these types now return the
standard ones.

* Renamed `Pipeline.drawFrom` to `Pipeline.readFrom` and
`GeneralStage.drainTo` to `GeneralStage.writeTo`.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=pipeline1]
----

* `ContextFactory` was renamed to `ServiceFactory` and we added support
for instance-wide initialization. `createFn` now takes
`ProcessorSupplier.Context` instead of just `JetInstance`. We also added
convenience methods in `ServiceFactories` to simplify constructing the
common variants:
+
[source]
----
include::{javasource}/migration/Migration.java[tag=serviceFactory1]
----

* `map/filter/flatMapUsingContext` was renamed to
`map/filter/flatMapUsingService`.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=pipeline2]
----

* `filterUsingServiceAsync` has been removed. Usages can be replaced with
`mapUsingServiceAsync`, which behaves like a filter if it returns a `null`
future or the returned future contains a `null` result:
+
[source]
----
include::{javasource}/migration/Migration.java[tag=async2]
----

* `flatMapUsingServiceAsync` has been removed. Usages can be replaced with
`mapUsingServiceAsync` followed by non-async `flatMap`:
+
[source]
----
include::{javasource}/migration/Migration.java[tag=async1]
----

* The methods `withMaxPendingCallsPerProcessor(int)` and
`withUnorderedAsyncResponses()` were removed from `ServiceFactory`. These
properties are relevant only in the context of asynchronous operations and
were used in conjunction with `GeneralStage.mapUsingServiceAsync(...)`. In
Jet 4.0 the `GeneralStage.mapUsingServiceAsync(...)` method has a new
variant with explicit parameters for the above settings.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=serviceFactory2]
----

* `com.hazelcast.jet.pipeline.Sinks#mapWithEntryProcessor` got a new
signature in order to accommodate the improved `EntryProcessor`, which
became more lambda-friendly in IMDG (see the
https://docs.hazelcast.org/docs/latest/manual/html-single/#introducing-lambda-friendly-interfaces[relevant section]
in the IMDG Migration Guide). The return type of `EntryProcessor` is now
an explicit parameter in ``mapWithEntryProcessor``'s method signature.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=entryProcessor1]
----

* HDFS source and sink methods are now `Hadoop.inputFormat` and
`Hadoop.outputFormat`.

* `MetricsConfig` is no longer part of `JetConfig`, but resides in the
IMDG `Config` class.
+
[source]
----
include::{javasource}/migration/Migration.java[tag=config3]
----

* `Traverser` type got a slight change in the `flatMap` lambda's generic
type wildcards. This change shouldn't affect anything in practice.

* In sources and sinks we changed the method signatures so that the lambda
becomes the last parameter, where applicable.

* `JetBootstrap.getInstance()` moved to `Jet.bootstrappedInstance()`
and now it automatically creates an isolated local instance when not
running through `jet submit`. If used from `jet submit`, the behaviour
remains the same.

* `JobConfig.addResource(...)` is now `addClasspathResource(...)`.

* `ResourceType`, `ResourceConfig` and `JobConfig.getResourceConfigs()`
are now labeled as private API and we discourage their direct usage. We
also renamed `ResourceType.REGULAR_FILE` to `ResourceType.FILE`, but this
is now an internal change.

[appendix]
= FAQ

You can refer to the https://jet.hazelcast.org/faq/[FAQ] page to see the
answers to frequently asked questions related to topics such as the
relationship and differences between Hazelcast Jet and Hazelcast IMDG,
Jet's APIs and roadmap.

[appendix]
= License Questions

Hazelcast Jet is distributed using the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2],
therefore permissions are granted to use, reproduce and distribute it
along with any kind of open source and closed source applications.

Depending on the used feature-set, Hazelcast Jet has certain runtime
dependencies which might have different licenses. Following are
dependencies and their respective licenses.

== Embedded Dependencies

Embedded dependencies are merged (shaded) with the Hazelcast Jet
codebase at compile-time. These dependencies become an integral part of
the Hazelcast Jet distribution.

For license files of embedded dependencies, please see the `license`
directory of the Hazelcast Jet distribution, available at our
https://jet.hazelcast.org/download/[download page].

=== minimal-json

minimal-json is a JSON parsing and generation library which is a part of
the Hazelcast Jet distribution. It is used for communication
between the Hazelcast Jet cluster and the Management Center.

minimal-json is distributed under the
http://opensource.org/licenses/MIT[MIT license] and offers the same
rights to add, use, modify, and distribute the source code as the Apache
License 2.0 that Hazelcast uses. However, some other restrictions might
apply.

=== picocli

picocli is a command line parser which is used for the implementation of
`jet` command line tool.

picocli is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Runtime Dependencies

Depending on the used features, additional dependencies might be added
to the dependency set. Those runtime dependencies might have other
licenses. See the following list of additional runtime dependencies.

=== Apache Hadoop

Hazelcast integrates with Apache Hadoop and can use it as a data
 sink or source. Jet has a dependency on the libraries required to
 read from and write to the Hadoop File System.

Apache Hadoop is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Apache Kafka

Hazelcast integrates with Apache Kafka and can make use of it as a
data sink or source. Hazelcast has a dependency on Kafka client
libraries.

Apache Kafka is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

=== Spring

Hazelcast integrates with Spring and can be configured using Spring
Context. Jet has a dependency on the libraries required to create a
Spring context.

Spring is distributed under the terms of the
http://www.apache.org/licenses/LICENSE-2.0[Apache License 2].

