/*
 * Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hazelcast.jet;

import com.hazelcast.jet.core.JobStatus;

/**
 * @since 5.3
 */
public interface JobListener {
    /**
     * @param description If the event is generated by the user, indicates the
     *        action, namely one of SUSPEND, RESUME, RESTART and CANCEL; if
     *        there is a failure, indicates the cause; otherwise, null.
     * @param userRequested Indicates whether the event is generated by the user
     *        via {@link Job#suspend()}, {@link Job#resume()},
     *        {@link Job#restart()} or {@link Job#cancel()}.
     */
    void jobStatusChanged(long jobId, JobStatus oldStatus, JobStatus newStatus,
                          String description, boolean userRequested);
}
