= JMS

JMS (Java Message Service) connector can be used both as a source and a
sink for infinite stream processing. The source supports the
exactly-once guarantee and sink supports the at-least-once guarantee.

In order to use JMS connector, the user should include a JMS Client in
classpath. IO failures are generally handled by the JMS Client and do
not cause the connector to fail. Most of the clients offer a
configuration parameter to enable auto-reconnection, refer to client
documentation for details.

== Using JMS as a Source

The JMS source opens one connection to the JMS server for each member.
Then each underlying worker of the source creates a session and a
message consumer using that connection. The user supplies necessary
functions to create the connection, session and message consumer.

If you have no processing guarantee enabled, the processor will consume
the messages in `DUPS_OK_ACKNOWLEDGE` mode. If the processing guarantee
is other than `NONE`, the processor will acknowledge messages in
transactions in the 2nd phase of the snapshot, that is after all
downstream stages fully processed the messages. Additionally, if the
processing guarantee is `EXACTLY_ONCE`, the processor will store message
IDs of the unacknowledged messages to the snapshot and should the job
fail after the snapshot was successful, but before Jet managed to
acknowledge the messages, the stored IDs will be used to filter out the
re-delivered messages.

Also keep in mind that exactly-once guarantee for JMS topic doesn't work
if you use a non-durable topic consumer. The broker doesn't store the
messages at all in this case.

The JMS source uses non-blocking API to receive the messages and
transforms each message to a desired output object using the supplied
projection function.

The following code snippets show streaming messages from a JMS queue and
a JMS topic using ActiveMQ JMS Client. For JMS topic, a shared durable
consumer is used:

[source]
----
include::{javasource}/integration/JMS.java[tag=s1]
----
[source]
----
include::{javasource}/integration/JMS.java[tag=s2]
----

The JMS topic, if not consumed by a shared consumer, is a
non-distributed source. If messages are consumed by multiple consumers,
all of them will get the same messages. Therefore the source operates on
a single member with local parallelism of 1. If you create a shared
consumer in the `consumerFn`, you should call `sharedConsumer(true)` on
the builder, as in the sample code above. For a queue we always assume a
shared consumer.

== Using JMS as a Sink

The JMS sink opens a connection to the JMS server for each member. Then
each underlying worker of the sink creates a session and a message
producer using that connection. The user supplies necessary functions
and parameters to create the connection and the messages.

The JMS sink uses the supplied function to create a `Message` object for
each input item. After a batch of messages is sent, sink commits the
session.

The following code snippets show writing to a JMS queue and a JMS topic
using ActiveMQ JMS Client.

[source]
----
include::{javasource}/integration/JMS.java[tag=s3]
----
[source]
----
include::{javasource}/integration/JMS.java[tag=s4]
----

== Supported implementations

We run our tests against ActiveMQ and RabbitMQ brokers. However any JMS
1.1 implementation should work.
