name: Create Tag

on:
  push:
    branches:
      - 'tag-v*'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create or update release tag
        run: |
          TAG_NAME="${GITHUB_REF_NAME#tag-}"

          # First try to create the release tag with `POST` as release tags
          # normally should not exist prior. If that fails, only then attempt to `PATCH`
          # existing release tag (useful in `sandbox` or when a post fix is applied and
          # tag needs refreshing)
          gh api \
            --method POST \
            repos/${GITHUB_REPOSITORY}/git/refs \
            -f ref=refs/tags/${TAG_NAME} \
            -f sha=${GITHUB_SHA} || \
          gh api \
            --method PATCH \
            repos/${GITHUB_REPOSITORY}/git/refs/tags/${TAG_NAME} \
            -f sha=${GITHUB_SHA} \
            -F force=true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Delete temp `tag-v*` branch
        if: always()
        run: |
          gh api \
            --method DELETE \
            repos/${GITHUB_REPOSITORY}/git/refs/heads/${GITHUB_REF_NAME}
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: hazelcast/docker-actions/slack-notification@master
        if: failure()
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_MONOREPO }}
          slack-channel: ${{ vars.MONOREPO_SLACK_CHANNEL }}
          status: failure
