name: Create Tag

on:
  push:
    branches:
      - 'tag-v*'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        run: |
          # Create-or-replace tag
          gh api \
            --method PATCH \
            repos/${GITHUB_REPOSITORY}/git/refs/tags/${GITHUB_REF_NAME#tag-}} \
            -f sha="${GITHUB_SHA}" \
            -f force=true

          # Delete branch
          gh api \
            --method DELETE \
            repos/${GITHUB_REPOSITORY}/git/refs/heads/${GITHUB_REF_NAME}
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: hazelcast/docker-actions/slack-notification@master
        if: failure()
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_MONOREPO }}
          slack-channel: ${{ vars.MONOREPO_SLACK_CHANNEL }}
