name: Create Tag

on:
  push:
    branches:
      - 'tag-v*'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Create Tag
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME}"
          TAG_NAME="${BRANCH_NAME#tag-}"          
          git tag --force $TAG_NAME
          git push origin --force $TAG_NAME
          git push origin --delete $BRANCH_NAME
      - uses: hazelcast/docker-actions/slack-notification@master
        if: failure()
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_MONOREPO }}
          slack-channel: "#monorepo-notifications"
