#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
#shellcheck source=bin-regular/common.sh

if [[ "$1" = "--help" ]] || [[ "$1" = "-h" ]]; then
    echo "Usage: jet-start [-d]"
    echo "  -d, --daemon   Starts Hazelcast Jet in daemon mode"
    exit 0
elif [[ "$1" = "-d" ]] || [[ "$1" = "--daemon" ]]; then
    DAEMON="true"
fi

. "$SCRIPT_DIR"/common.sh

JAVA_OPTS_ARRAY=(\
$JDK_OPTS \
"-Dhazelcast.logging.type=log4j" \
"-Dlog4j.configuration=file:$JET_HOME/config/log4j.properties" \
"-Djet.home=$JET_HOME" \
"-Dhazelcast.config=$JET_HOME/config/hazelcast.yaml" \
"-Dhazelcast.jet.config=$JET_HOME/config/hazelcast-jet.yaml" \
$JAVA_OPTS \
)

echo "########################################"
echo "# JAVA=$JAVA"
echo "# JAVA_OPTS=${JAVA_OPTS_ARRAY[*]}"
echo "# CLASSPATH=$CLASSPATH"
echo "########################################"

if [[ "$DAEMON" = "true" ]]; then
    mkdir -p $JET_HOME/logs
    JET_LOG="$JET_HOME/logs/hazelcast-jet.out"
    echo "Starting Hazelcast Jet in daemon mode. Standard out and error will be written to $JET_LOG"
    nohup $JAVA "${JAVA_OPTS_ARRAY[@]}" -cp "$CLASSPATH" com.hazelcast.jet.server.JetMemberStarter > "$JET_LOG" 2>&1 &
else
    echo "Starting Hazelcast Jet"
    set -x
    $JAVA "${JAVA_OPTS_ARRAY[@]}" -cp "$CLASSPATH" com.hazelcast.jet.server.JetMemberStarter
fi